"""Unit tests for the parity audit (WP 4.1): dump parsing, version-line
stripping, and the image/CI diff."""

from __future__ import annotations

from girder.github.parity import (
    compare,
    parse_dump,
    parse_version_line,
    render_dump,
)


def test_parse_dump_tool_eq_version_lines_and_comments() -> None:
    dump = parse_dump("# generated by ci-env-dump.sh\npython=3.12.3\npip=24.0\n\npytest=8.3.2\n")
    assert dump == {"python": "3.12.3", "pip": "24.0", "pytest": "8.3.2"}


def test_parse_version_line_strips_tool_prefix() -> None:
    assert parse_version_line("python", "Python 3.12.3\n") == "3.12.3"
    assert parse_version_line("pip", "pip 24.0 from /usr/lib (python 3.12)\n") == (
        "24.0 from /usr/lib (python 3.12)"
    )
    assert parse_version_line("pytest", "pytest 8.3.2\n\nplugins: ...\n") == "8.3.2"
    assert parse_version_line("tool", "") is None


def test_compare_reports_only_divergence_sorted() -> None:
    image = {"python": "3.12.3", "pip": "24.0", "pytest": "8.3.2"}
    ci = {"python": "3.12.3", "pip": "23.2", "node": "20.x"}
    deltas = compare(image, ci)
    assert [(d.tool, d.image_version, d.ci_version) for d in deltas] == [
        ("node", None, "20.x"),
        ("pip", "24.0", "23.2"),
        ("pytest", "8.3.2", None),
    ]
    assert all(d.diverged for d in deltas)


def test_compare_identical_is_empty() -> None:
    assert compare({"python": "3.12.3"}, {"python": "3.12.3"}) == []


def test_render_dump_round_trips_through_parse() -> None:
    versions = {"pytest": "8.3.2", "python": "3.12.3", "pip": "24.0"}
    text = render_dump(versions)
    assert text == "pip=24.0\npytest=8.3.2\npython=3.12.3\n"
    assert parse_dump(text) == versions
