"""Unit tests for PR-body template rendering (WS-05 / WP 9.3): the built-in
Jinja2 fallback with real run data, and the ``[github] pr_template`` custom
override. The legacy plain-text format (no run_id — the delivery pump's call
shape today) is covered by test_github_client.py."""

from __future__ import annotations

from pathlib import Path

from girder.config import GithubConfig, Secrets, Settings
from girder.github.client import GitHubClient
from girder.guard.redact import Redactor


def make_client(pr_template: str | None = None) -> GitHubClient:
    return GitHubClient(
        Settings(github=GithubConfig(api_url="http://github.test", pr_template=pr_template)),
        Secrets(github_token="t"),
        Redactor(),
        None,  # type: ignore[arg-type]  # pr_body never touches the DB
        repo_path=Path("/tmp"),
        owner_repo=("acme", "widget"),
    )


TASKS = [
    {"title": "Implement divide", "task_type": "code_change", "status": "completed"},
    {"title": "Add divide tests", "task_type": "test", "status": "completed"},
]


def test_builtin_template_renders_real_run_data() -> None:
    body = make_client().pr_body(
        intent="Users can divide numbers.",
        task_lines=[],
        criteria=["divide returns the quotient"],
        spend_usd=0.123456,
        run_id="b7e23ec29af22b0b4e99da6a1b1e2c9d",
        tasks=TASKS,
        total_attempts=5,
    )
    assert "## Summary" in body
    assert "Users can divide numbers." in body
    assert "- **Implement divide** (`code_change`) — completed" in body
    assert "- **Add divide tests** (`test`) — completed" in body
    assert "$0.1235" in body  # %.4f formatting
    assert "Attempts: 5" in body
    assert (
        "[girder/b7e23ec2](http://127.0.0.1:8787/runs/b7e23ec29af22b0b4e99da6a1b1e2c9d)"
        in body
    )
    assert "Generated by [Girder]" in body


def test_custom_template_overrides_builtin() -> None:
    template = (
        "# Run {{ run_id[:8] }}\n\n{{ intent }}\n\nCost: ${{ '%.2f'|format(total_cost_usd) }}\n"
    )
    body = make_client(template).pr_body(
        intent="Add a divide endpoint.",
        task_lines=[],
        criteria=[],
        spend_usd=1.5,
        run_id="b7e23ec29af22b0b4e99da6a1b1e2c9d",
        tasks=TASKS,
        total_attempts=1,
    )
    assert body.startswith("# Run b7e23ec2")
    assert "Add a divide endpoint." in body
    assert "Cost: $1.50" in body
    assert "## Tasks completed" not in body  # builtin not used


def test_fallback_maps_task_lines_when_task_dicts_missing() -> None:
    body = make_client().pr_body(
        intent="i",
        task_lines=["Do the thing"],
        criteria=[],
        spend_usd=0.0,
        run_id="abc123456789",
    )
    assert "- **Do the thing** (``) —" in body


def test_console_url_uses_web_config() -> None:
    from girder.config import WebConfig

    client = GitHubClient(
        Settings(
            github=GithubConfig(api_url="http://github.test"),
            web=WebConfig(host="localhost", port=9000),
        ),
        Secrets(github_token="t"),
        Redactor(),
        None,  # type: ignore[arg-type]
        repo_path=Path("/tmp"),
        owner_repo=("acme", "widget"),
    )
    body = client.pr_body(
        intent="i", task_lines=[], criteria=[], spend_usd=0.0, run_id="abc123456789"
    )
    assert "http://localhost:9000/runs/" in body
